name: Deploy Flask App

on:
  push:
    branches:
      - main  # or 'master' depending on your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Your steps go here
